nelc/futurex-openedx-extensions

futurex_openedx_extensions/dashboard/serializers.py, test_utils/edx_platform_mocks/fake_models/functions.py, test_utils/edx_platform_mocks/fake_models/models.py
Ensure the user is passed as User object and not its ID
Fixes Sentry error: https://nelc-uk.sentry.io/issues/5416270924/?project=6400062&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1
```json
[
{
"id": "course-v1:Demo+1+2022-m4",
"status": "active",
"self_paced": false,
"start_date": "2017-01-01T10:00:00Z",
"end_date": "2050-01-01T10:00:00Z",
"start_enrollment_date": null,
"end_enrollment_date": null,
"display_name": "MITx Grading Library",
"image_url": "/asset-v1:Demo+1+2022-m4+type@asset+block@mitx.jpg",
"org": "Demo",
"tenant_ids": [
1,
100
],
"author_name": null,
"enrollment_date": "2024-04-26T19:40:03.782137+03:00",
"last_activity": "2024-04-26T19:40:03.782137+03:00",
"certificate_url": null,
"progress_url": null,
"grades_url": null,
"progress": { …
```
=> fix: learner course serialization errors

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/tenants.py, test_settings.py, tests/test_dashboard/test_views.py
Disabling rate-limit since it's interfering with development and QA tests. We will implement API key soon https://github.com/nelc/futurex-openedx-extensions/issues/35
=> fix: disable rate-limit

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/urls.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/extractors.py, futurex_openedx_extensions/helpers/roles.py, setup.cfg, tests/base_test_data.py, tests/conftest.py, tests/fixture_helpers.py, tests/test_dashboard/test_serializers.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_roles.py
feat: user management APIs - GET
=> feat: user management APIs - GET

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/caching.py, futurex_openedx_extensions/helpers/constants.py, futurex_openedx_extensions/helpers/exceptions.py, futurex_openedx_extensions/helpers/extractors.py, futurex_openedx_extensions/helpers/roles.py, futurex_openedx_extensions/helpers/tenants.py, futurex_openedx_extensions/helpers/users.py, test_utils/edx_platform_mocks/fake_models/functions.py, test_utils/edx_platform_mocks/fake_models/models.py, tests/fixture_helpers.py, tests/test_dashboard/test_details/test_details_courses.py, tests/test_dashboard/test_serializers.py, tests/test_dashboard/test_statistics/test_courses.py, tests/test_dashboard/test_statistics/test_learners.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_exceptions.py, tests/test_helpers/test_extractors.py, tests/test_helpers/test_roles.py, tests/test_helpers/test_tenants.py, tests/test_helpers/test_users.py
feat: user roles edit APIs
* add user roles: done
* delete roles for user: done
* update roles for user: done
=> feat: user roles edit APIs

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/helpers/course_creator_manager.py, futurex_openedx_extensions/helpers/exceptions.py, futurex_openedx_extensions/helpers/roles.py, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/quality.txt, requirements/test.in, requirements/test.txt, test_utils/edx_platform_mocks/fake_models/models.py, test_utils/edx_platform_mocks/lms/djangoapps/grades/models.py, test_utils/edx_platform_mocks/organizations/models.py, tests/test_helpers/test_course_creator_manager.py, tests/test_helpers/test_roles.py
refactor: manage CourseCreator operations through a new manager
=> refactor: manage CourseCreator operations through a new manager

futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/helpers/roles.py, tests/test_dashboard/test_serializers.py, tests/test_helpers/test_roles.py
Related Issue: https://github.com/nelc/futurex-openedx-extensions/issues/69#issue-2521426679
=> Add global roles data to course roles API

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/details/learners.py, tests/test_dashboard/test_details/test_details_learners.py, tests/test_dashboard/test_views.py
fix: learners/v1/learners API not excluding staff
fixes: https://github.com/nelc/futurex-openedx-extensions/issues/65
=> fix: learners/v1/learners API not excluding staff

futurex_openedx_extensions/dashboard/details/learners.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/statistics/learners.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/permissions.py, futurex_openedx_extensions/helpers/querysets.py, futurex_openedx_extensions/helpers/roles.py, futurex_openedx_extensions/helpers/users.py, tests/conftest.py, tests/fixture_helpers.py, tests/test_dashboard/test_details/test_details_courses.py, tests/test_dashboard/test_details/test_details_learners.py, tests/test_dashboard/test_serializers.py, tests/test_dashboard/test_statistics/test_certificates.py, tests/test_dashboard/test_statistics/test_courses.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_permissions.py, tests/test_helpers/test_querysets.py, tests/test_helpers/test_roles.py, tests/test_helpers/test_users.py
- **refactor: no logic change - more readable code for permissions**: no logic change at all. Just a few code changes for better readability
- **refactor: no logic change - move get_learners_search_queryset**: no logic change at all. Just moving the function to `querysets.py` to be reusable by other modules
=> refactor: more readable code for permissions

futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/exceptions.py, futurex_openedx_extensions/helpers/export_data.py, tests/test_helpers/test_export_data.py
=> csv generate - deliverable 1 - generate file without task

tests/conftest.py, tests/test_dashboard/test_serializers.py, tests/test_helpers/test_course_creator_manager.py
chore: test course_creator_group in UserRolesSerializer
This was an attempt to fix https://github.com/nelc/futurex-openedx-extensions/issues/87. But tests showed that there is no bug. It's bad data in production. Details are in the related issue
=> chore: test course_creator_group in UserRolesSerializer

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/details/learners.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/helpers/querysets.py, futurex_openedx_extensions/helpers/roles.py, test_utils/edx_platform_mocks/custom_reg_form/models.py, test_utils/edx_platform_mocks/fake_models/models.py, tests/base_test_data.py, tests/conftest.py, tests/test_dashboard/test_serializers.py, tests/test_dashboard/test_views.py
feat: add national ID from ExtraInfo
=> feat: add national ID from ExtraInfo

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/helpers/roles.py, tests/test_helpers/test_roles.py
fix: partial clean-up not working properly
fixes: https://github.com/nelc/futurex-openedx-extensions/issues/109
=> fix: partial clean-up not working properly

futurex_openedx_extensions/helpers/roles.py, futurex_openedx_extensions/helpers/signals.py, tests/conftest.py, tests/test_helpers/test_roles.py, tests/test_helpers/test_signals.py
fix: adding roles must add UserSignupSource records
Fixes: https://github.com/nelc/futurex-openedx-extensions/issues/91
=> fix: adding roles must add UserSignupSource records

futurex_openedx_extensions/helpers/theme.py, test_settings.py, tests/test_helpers/test_theme.py
Add helper method to get FutureX Dashboard URL for accessible tenant.
=> feat: add helper method to get fx dashboard url

futurex_openedx_extensions/__init__.py
=> chore: bump version 0.9.6

futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/helpers/tasks.py, tests/test_helpers/test_tasks.py
feat: show progress of data export tasks
=> feat: show progress of data export tasks

futurex_openedx_extensions/__init__.py
=> chore: bump version to v0.9.9

futurex_openedx_extensions/helpers/roles.py, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/quality.txt, requirements/test.in, requirements/test.txt
chore: add django-filter to tests requirements
=> chore: add django-filter to tests requirements

futurex_openedx_extensions/dashboard/custom_serializers.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/certificates.py, futurex_openedx_extensions/helpers/exceptions.py, test_utils/edx_platform_mocks/fake_models/functions.py, test_utils/edx_platform_mocks/fake_models/models.py, test_utils/edx_platform_mocks/lms/djangoapps/grades/context.py, test_utils/edx_platform_mocks/lms/djangoapps/grades/models.py, test_utils/edx_platform_mocks/openedx/core/lib/courses.py, tests/test_dashboard/test_custom_serializers.py, tests/test_dashboard/test_serializers.py, tests/test_helpers/test_certificates.py
feat: add optional fields to course learners' API
to include the score details, the caller must include the `csv_export` or `exam_scores` tag to the `optional_field_tags` parameter
```
GET /api/fx/learners/v1/learners/{{course_id}}/?optional_field_tags=csv_export
```
Scores are separated into columns, two columns for each graded subsection. One column for earned score, and another for the possible score. A placeholder string value `no attempt` will be set for the field if the learner hasn't attempt to answer the exam's problems yet
The name of the column is in the following format:
```
earned|possible - <grade_type_as_in_grading_settings>[ <sequence_if_more_than_one_subsection_of_the_same_type>][: <subsection_display_name>]
```
`subsection_display_name` can be omitted by passing a special …
=> feat: add optional fields to course learners API

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/helpers/theme.py, test_settings.py, tests/test_helpers/test_theme.py
=> fix: dashboard URL

futurex_openedx_extensions/__init__.py
chore: bump version to v0.9.16
=> chore: bump version to v0.9.16

futurex_openedx_extensions/dashboard/views.py
feat: add csv export support to courses and learners APIs
=> feat: add csv export support to courses and learners APIs

futurex_openedx_extensions/helpers/settings/common_production.py, tests/test_helpers/test_apps.py
fix: default course-effort-value
=> fix: default course-effort-value

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/helpers/export_csv.py, tests/test_helpers/test_export_csv.py
feat: CSV export to be saved as private
resolves https://github.com/nelc/futurex-openedx-extensions/issues/153
=> feat: CSV export to be saved as private

.github/ISSUE_TEMPLATE/issue_template_bug.md, .github/ISSUE_TEMPLATE/issue_template_feature.md, .github/ISSUE_TEMPLATE/issue_template_task.md, .github/PULL_REQUEST_TEMPLATE.md
add templates for issues: **Bug**, **Feature**, and **Task**
=> chore: issue templates

.github/workflows/add-issue-to-project.yml
Automatically add new issues to ZeitLabs project for Nelc, to easily track progress
=> chore: auto add new issues to project

futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/helpers/settings/common_production.py, futurex_openedx_extensions/helpers/tenants.py, test_utils/edx_platform_mocks_shared/common/djangoapps/third_party_auth/models.py, test_utils/edx_platform_mocks_shared/fake_models/models.py, test_utils/test_settings_common.py, tests/test_dashboard/test_serializers.py, tests/test_helpers/test_tenants.py
Add a brief description of the changes made in this PR.
=> feat: add nafath id to enrollment api

futurex_openedx_extensions/helpers/tenants.py
Cache the list of Nafath sites. We do that by leveraging the function that's already cached `get_all_tenants_info`
=> feat: cache the list of Nafath sites

futurex_openedx_extensions/__init__.py
=> chore: Bump version to v0.10.2

futurex_openedx_extensions/dashboard/docs_src.py
=> docs: enhance documentation

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/views.py
=> fix: add auth class to AccessibleTenantsInfoViewV2

futurex_openedx_extensions/dashboard/details/courses.py, futurex_openedx_extensions/dashboard/details/learners.py, futurex_openedx_extensions/dashboard/statistics/certificates.py
Fix the a bug. Certificates count is not excluding disabled users.
=> fix: certificates count is not excluding disabled users

futurex_openedx_extensions/dashboard/details/learners.py, futurex_openedx_extensions/dashboard/docs_src.py, futurex_openedx_extensions/dashboard/views.py, tests/test_dashboard/test_details/test_details_learners.py, tests/test_dashboard/test_views.py
Ability to filter on enrollments count in Learners API. See the related issue for more details
=> feat: ability to filter on enrollments count in Learners API

futurex_openedx_extensions/dashboard/docs_src.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/mysql_functions.py, futurex_openedx_extensions/helpers/tenants.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_tenants.py
Contains code for following APIS
`POST /api/fx/config/v1/publish`
`GET /api/fx/config/v1/values`
Related issues:
https://github.com/nelc/futurex-openedx-extensions/issues/244
https://github.com/nelc/futurex-openedx-extensions/issues/242
=> feat: theme config values and publish api implementation #246

futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/tenants.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_tenants.py
fix: tenant permissions for theme apis
=> fix: tenant permissions for theme apis

futurex_openedx_extensions/__init__.py
chore: bump version to v0.10.4
=> chore: bump version to v0.10.4

futurex_openedx_extensions/dashboard/details/courses.py, futurex_openedx_extensions/helpers/converters.py, futurex_openedx_extensions/helpers/querysets.py, futurex_openedx_extensions/helpers/roles.py, tests/test_helpers/test_converters.py, tests/test_helpers/test_querysets.py
feat: ability to search using Arabic names and Indian numerals
=> feat: ability to search using Arabic names and Indian numerals

futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/tenants.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_tenants.py
Fix the behavior of the system that is not allowing system staff users to access the APIs unless an explicit course-access-role is declared
=> fix: system staff users access to config APIs

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/helpers/tasks.py, tests/test_helpers/test_tasks.py
=> fix: CSV export site-domain

futurex_openedx_extensions/dashboard/docs_src.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/urls.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/extractors.py, futurex_openedx_extensions/helpers/library.py, test_utils/edx_platform_mocks_shared/common/djangoapps/student/auth.py, test_utils/edx_platform_mocks_shared/common/djangoapps/student/roles.py, test_utils/edx_platform_mocks_shared/fake_models/classes.py, test_utils/edx_platform_mocks_shared/fake_models/functions.py, test_utils/edx_platform_mocks_shared/xmodule/modulestore/__init__.py, test_utils/edx_platform_mocks_shared/xmodule/modulestore/django.py, test_utils/edx_platform_mocks_shared/xmodule/modulestore/exceptions.py, tests/test_dashboard/test_serializers.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_extractors.py, tests/test_helpers/test_library.py
https://github.com/nelc/futurex-openedx-extensions/issues/118
=> feat: library list api

futurex_openedx_extensions/dashboard/views.py
fix: missing auth class for the enrollments API
=> fix: missing auth class for the enrollments API

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/templates/set_theme_preview.html, futurex_openedx_extensions/dashboard/urls.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/tenants.py, test_utils/test_settings_common.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_tenants.py
=> feat: add theme preview API

futurex_openedx_extensions/dashboard/docs_src.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/helpers/tenants.py, test_utils/edx_platform_mocks_shared/xmodule/modulestore/django.py, tests/base_test_data.py, tests/test_dashboard/test_views.py
](https://github.com/nelc/futurex-openedx-extensions/issues/286)
=> fix: library create api for org

futurex_openedx_extensions/dashboard/urls.py, test_utils/edx_platform_mocks_shared/fake_models/functions.py, test_utils/edx_platform_mocks_shared/lms/djangoapps/static_template_view/views.py
feat: add route for custom pages
=> feat: add route for custom pages

futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/settings/common_production.py, test_utils/test_settings_common.py, tests/test_dashboard/test_views.py
feat: temporary disable of config validation
=> feat: temporary disable of config validation

futurex_openedx_extensions/__init__.py
chore: bump version to v0.10.8
=> chore: bump version to v0.10.8

futurex_openedx_extensions/__init__.py
chore: bump version to 0.10.11
=> chore: bump version to 0.10.11

futurex_openedx_extensions/__init__.py
=> chore: bump version 0.10.12.3

futurex_openedx_extensions/dashboard/docs_src.py, futurex_openedx_extensions/dashboard/urls.py, futurex_openedx_extensions/dashboard/views.py, tests/test_dashboard/test_views.py
=> feat: tenant-info API

futurex_openedx_extensions/dashboard/docs_src.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/settings/common_production.py, futurex_openedx_extensions/dashboard/views.py, test_utils/edx_platform_mocks_shared/fake_models/classes.py, test_utils/test_settings_common.py, tests/test_dashboard/test_apps.py, tests/test_dashboard/test_serializers.py, tests/test_dashboard/test_views.py
feat: more optional fields to the course creation API
=> feat: more optional fields to the course creation API

futurex_openedx_extensions/dashboard/serializers.py
fix: read language choices from settings correctly
=> fix: read language choices from settings correctly

futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/models.py, futurex_openedx_extensions/helpers/tenants.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_models.py, tests/test_helpers/test_tenants.py
chore: one place to check for the draft revision_id
After https://github.com/nelc/futurex-openedx-extensions/pull/339
=> chore: one place to check for the draft revision_id

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/helpers/certificates.py, futurex_openedx_extensions/helpers/tenants.py, tests/test_dashboard/test_serializers.py, tests/test_helpers/test_certificates.py, tests/test_helpers/test_tenants.py
fix: wrong domain for generated urls
=> fix: wrong domain for generated urls
