futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/urls.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/permissions.py, tests/base_test_data.py, tests/test_base_test_data.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_permissions.py
feat: add version info API
The deployment process on staging and production is a bit complicated in terms of tracing deployed parts. Adding this API to easily check the deployed extensions version
```
GET /api/fx/version/v1/info/
```
allowed for only staff and super users. Result:
```json
{
"version": "0.3.8"
}
```
=> feat: add version info API

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/details/learners.py, futurex_openedx_extensions/dashboard/statistics/learners.py, tests/base_test_data.py, tests/test_dashboard/test_details/test_details_courses.py, tests/test_dashboard/test_details/test_details_learners.py, tests/test_dashboard/test_statistics/test_learners.py, tests/test_helpers/test_tenants.py
Enrollments with `is_active` set to `False` must be excluded from all calculations and results. Except for checking if a user is related to a certain tenant or not
=> fix: some queries include inactive enrollments

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/details/courses.py, futurex_openedx_extensions/dashboard/statistics/courses.py, futurex_openedx_extensions/dashboard/urls.py, futurex_openedx_extensions/dashboard/views.py, tests/test_dashboard/test_details/test_details_courses.py, tests/test_dashboard/test_statistics/test_courses.py, tests/test_dashboard/test_views.py
feat: global courses rating API
```
GET api/fx/statistics/v1/rating/?tenant_ids=1,2,3
```
It'll only return the rating for accessible courses. For example, if the user has access to 20 courses out of 20 in the tenant; the result will be the average rating for only the two accessible courses
=> feat: global courses rating API

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/statistics/courses.py, tests/test_dashboard/test_statistics/test_courses.py, tests/test_dashboard/test_views.py
fix: None value returned by Rating API
Before the fix: the API is crashing on tenants with no rating records
=> fix: None value returned by Rating API

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/statistics/certificates.py, futurex_openedx_extensions/dashboard/statistics/courses.py, futurex_openedx_extensions/dashboard/statistics/learners.py, futurex_openedx_extensions/helpers/roles.py, futurex_openedx_extensions/helpers/tenants.py, test_utils/edx_platform_mocks/fake_models/models.py, tests/base_test_data.py, tests/conftest.py, tests/fixture_helpers.py, tests/test_dashboard/test_details/test_details_courses.py, tests/test_dashboard/test_serializers.py, tests/test_dashboard/test_statistics/test_certificates.py, tests/test_dashboard/test_statistics/test_courses.py, tests/test_dashboard/test_statistics/test_learners.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_extractors.py, tests/test_helpers/test_permissions.py, tests/test_helpers/test_querysets.py, tests/test_helpers/test_roles.py, tests/test_helpers/test_tenants.py
* fix: key and collation of `CourseAccessRole` in tests: SQLite is performing `in` operations as case-sensitive unless it is explicitly defined as `NOCASE`. We need to test scenarios where `org` in roles is not the same as the one in organizations (case-sensitivity-wise)
* fix: test-data to include case-insensitive orgs: this will pinpoint python code that compares orgs as case-sensitive
* fix: `CourseAccessRole` is always case-insensitive
=> fix: CourseAccessRole is always case-insensitive

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/details/learners.py, futurex_openedx_extensions/dashboard/statistics/learners.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/querysets.py, futurex_openedx_extensions/helpers/tenants.py, tests/base_test_data.py, tests/conftest.py, tests/fixture_helpers.py, tests/test_dashboard/test_details/test_details_learners.py, tests/test_dashboard/test_statistics/test_learners.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_querysets.py, tests/test_helpers/test_tenants.py
We now have `UserSignupSource` filled on course-enrollment! refactoring a few functions accordingly 
- **refactor: use UserSignupSource to count learners in tenants**: this will also enhance performance
- **refactor: get_user_id_from_username_tenants**: to use UserSignupSource for better performance
- **refactor: get_learners_queryset to use UserSignupSource**: just filter on UserSignupSource for better performance
=> refactor: Better use of UserSignupSource

futurex_openedx_extensions/dashboard/details/courses.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/views.py, tests/test_dashboard/test_details/test_details_courses.py, tests/test_dashboard/test_serializers.py
**Related Issue:** https://github.com/nelc/futurex-openedx-extensions/issues/60
**API**: GET <LMS_URL>/api/fx/courses/v1/courses/
Update courses list API to return completion rate.
**SS from local setup:**
=> Add 'completion rate' to courses list api

futurex_openedx_extensions/dashboard/statistics/courses.py, futurex_openedx_extensions/dashboard/views.py, tests/base_test_data.py, tests/test_dashboard/test_statistics/test_courses.py, tests/test_dashboard/test_views.py
**feat: add enrollments count statistics**
a new option in statistics-totals API to give the total number of enrollments in the given tenants and accessible courses
```
GET api/fx/statistics/v1/total_counts/?stats=enrollments
```
**feat: add limited_access flag to statistics API**
an extra field in the response:
```json
{
...
"limited_access": false
}
```
the value is `true` if the user has only course-specific roles in the given tenants
=> feat: add enrollments count statistics

futurex_openedx_extensions/dashboard/serializers.py, tests/test_dashboard/test_serializers.py
fix: certificate-url in learner's details
Fixes: https://github.com/nelc/futurex-openedx-extensions/issues/96
=> fix: certificate-url in learner's details

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/urls.py, futurex_openedx_extensions/dashboard/views.py, tests/test_dashboard/test_views.py
feat: add my-roles API
All tenants:
```
GET api/fx/roles/v1/my_roles/
```
or specific tenants:
```
GET api/fx/roles/v1/my_roles/?tenant_ids=4
```
It'll work and return a result as long as the user is a system-staff, or has at least one role in the tenant. The result is the same one from get-users-roles API, but for one record with no list. Example:
```json
{
"user_id": 12,
"email": "shadinaif+2@gmail.com",
"username": "shadinaif",
"full_name": "Shadi Naif",
"alternative_full_name": "",
"is_staff_user": false,
"global_roles": [],
"tenants": {
"4": {
"tenant_roles": [
"data_researcher"
],
"course_roles": {}
}
}
}
```
=> feat: add my-roles API

futurex_openedx_extensions/dashboard/custom_serializers.py, tests/test_dashboard/test_custom_serializers.py
feat: implement Optional Fields
This will help us use the same endpoint and the same serializer to return extra fields in the result
One needed use-case is the need for extra columns in the exported files that are not available in the dashboard UI view. We don't include these columns (fields) because they need an intense process that will make the view very slow for no reason. But when these fields are explicitly requested; the view will include them in the result
For example, the following is a normal call to the API
```
GET /api/fx/learners/v1/learners/course-v1:ORG+1+1/
```
And the following has the same results above as a CSV download:
```
GET /api/fx/learners/v1/learners/course-v1:ORG+1+1/?download=csv
```
And the following is the same CSV download above, plus adding all extra fields …
=> feat: implement Optional Fields

futurex_openedx_extensions/helpers/export_mixins.py, tests/test_helpers/test_export_mixins.py
Updated response:
```
{
"success": "Task initiated successfully with id: 56",
"export_task_id": 56
}
```
=> fix: add task id in generate csv download task response

futurex_openedx_extensions/helpers/constants.py, futurex_openedx_extensions/helpers/extractors.py, futurex_openedx_extensions/helpers/roles.py, test_utils/edx_platform_mocks/xmodule/modulestore/django.py, tests/test_helpers/test_extractors.py, tests/test_helpers/test_roles.py
Add library roles and library_ids support for course access role APIs
Following are roles details
- staff role -> can be tenant wide or library specific.
- instructor role -> can be tenant wide or library specific.
- library_user -> only valid for library_ids, can not be set tenant wide.
Related Issue: https://github.com/nelc/futurex-openedx-extensions/issues/107
=> feat: add library roles support for roles API

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/filters.py
Added search on notes and filename
`GET /api/fx/export/v1/tasks/?search_text=abc`
It will return result where notes, filename contain 'abc'
=> feat: add search on notes and filename for csv tasks

futurex_openedx_extensions/helpers/permissions.py, futurex_openedx_extensions/helpers/roles.py, tests/conftest.py, tests/test_helpers/test_permissions.py, tests/test_helpers/test_roles.py
fix: global roles do not have access to views
Scenario: the user has one role `support`
**Before the fix:** the user is not allowed to access the view
**After the fix:** the user is allowed to access the view
=> fix: global roles do not have access to views

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/details/courses.py, futurex_openedx_extensions/dashboard/details/learners.py, futurex_openedx_extensions/helpers/apps.py, futurex_openedx_extensions/helpers/exceptions.py, futurex_openedx_extensions/helpers/monkey_patches.py, futurex_openedx_extensions/helpers/pagination.py, futurex_openedx_extensions/helpers/querysets.py, tests/test_helpers/test_monkey_patches.py, tests/test_helpers/test_pagination.py, tests/test_helpers/test_querysets.py
* feat: removable annotations on pagination
* feat: apply removable annotations on applicable querysets
* avoid using `Count` if removing the annotation is needed. Use `Subquery` instead
=> feat: removable annotations on pagination

futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/helpers/admin.py, tests/test_dashboard/test_serializers.py
Fixes for following issues:
https://github.com/nelc/futurex-openedx-extensions/issues/144
https://github.com/nelc/futurex-openedx-extensions/issues/141
=> fix: issue 114 for data export django admin and 147 for course score in course learners api

futurex_openedx_extensions/dashboard/details/learners.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/urls.py, futurex_openedx_extensions/dashboard/views.py, tests/test_dashboard/test_details/test_details_learners.py, tests/test_dashboard/test_serializers.py, tests/test_dashboard/test_views.py
Add enrollment api.
**Example usage:**
To get all enrolments:
`/api/fx/learners/v1/enrollments/`
```
[ 
{
"user_id": 10,
"full_name": "user1",
"alternative_full_name": "عالي",
"username": "user1",
"national_id": "",
"email": "[user1@example.com](mailto:user1@example.com)",
"mobile_no": null,
"year_of_birth": null,
"gender": "",
"gender_display": null,
"date_joined": "2024-11-08T12:31:06.322903Z",
"last_login": "2024-11-15T08:23:03.539659Z",
"certificate_available": false,
"course_score": null,
"active_in_course": false,
"course_id": "course-v1:bragi_org+111+11"
},
]
...
```
To get all enrolments - with complete details
`/api/fx/learners/v1/enrollments/?optional_field_tags=__all__`
```
[
{
"user_id": 10,
"full_name": "user1",
"alternative_full_name": "عالي",
"username": "user1", …
```
=> feat: add learners enrolment list api

futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/roles.py, tests/test_dashboard/test_serializers.py, tests/test_helpers/test_roles.py
feat: ability to exclude global roles from GET-roles API
* Removing exclusion filter options: `exclude_tenant_roles` and `exclude_course_roles`
* Replacing them with one exclusion filter option `excluded_role_types` that accepts any combination of `global`, `tenant`, and `course`
show only users having global roles ((do not show users having tenant-wise or course-specific roles, unless another role exists))
```
GET /api/fx/roles/v1/user_roles/?excluded_role_types=tenant,course
```
do not show users having global roles, unless another role exists
```
GET /api/fx/roles/v1/user_roles/?excluded_role_types=global
```
do not show users having course-specific roles, unless another role exists
```
GET /api/fx/roles/v1/user_roles/?excluded_role_types=course
```
invalid types are ignored. The …
=> feat: ability to exclude global roles from GET-roles API

futurex_openedx_extensions/dashboard/details/learners.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/extractors.py, tests/test_dashboard/test_details/test_details_learners.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_extractors.py, tests/test_helpers/test_roles.py
Related Issue: 
https://github.com/nelc/futurex-openedx-extensions/issues/154
https://github.com/nelc/futurex-openedx-extensions/issues/155
=> fix: issue-154 for enrollment api

futurex_openedx_extensions/dashboard/details/learners.py, futurex_openedx_extensions/dashboard/views.py, tests/test_dashboard/test_details/test_details_learners.py, tests/test_dashboard/test_views.py
Allow user to filter enrollments suing both user_ids and usernames.
GET /api/fx/learners/v1/enrollments/?user_ids=1,2&usernames=user1,user4 -> It will filter on users 1, 2, and 4
=> fix: add usernames filter to enrollment API

futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/roles.py, tests/test_helpers/test_roles.py
Related Issue: https://github.com/nelc/futurex-openedx-extensions/issues/161
=> feat: handle fxcoded exception and return readable response

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/upgrade/utils.py, test_settings_palm.py, test_settings_redwood.py, test_utils/edx_platform_mocks_shared/openedx/core/release.py, tests/test_upgrade/test_utils.py
feat: select the correct version according to edx-platform release-line
* `palm` release will use `palm`
* releases before `palm` will use `palm`
* `redwood` release will use `redwood`
* releases after `redwood` (including `master`) will use `redwood`
=> feat: select the correct version according to edx-platform release-line

futurex_openedx_extensions/dashboard/views.py, tests/base_test_data.py, tests/test_dashboard/test_views.py
feat: add `unique_leanrers` statistics
```
GET api/fx/statistics/v1/total_counts/?stats=unique_leanrers
```
Unlike `stats=leanrers`; this will not recalculate the same learner having a record in multiple tenants
**Front-end Note**
This new stat is not useful for now because all the dashboard views are single-tenant views. This will be useful for the data-team; and will be useful in the future when we implement the Staff-View with multi-tenants
=> feat: add unique_leanrers statistics

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/docs_src.py, futurex_openedx_extensions/dashboard/docs_utils.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/models.py, requirements/test-constraints-palm.txt, requirements/test-constraints-redwood.txt, requirements/test.in, tests/test_dashboard/test_docs_utils.py
feat: swagger docs
it's on staging now: https://sn.stage.nelp.gov.sa/api-docs/#/fx
=> feat: swagger docs

futurex_openedx_extensions/dashboard/details/learners.py, futurex_openedx_extensions/dashboard/docs_src.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/views.py, tests/test_dashboard/test_details/test_details_learners.py, tests/test_dashboard/test_serializers.py
Related Issue: https://github.com/nelc/futurex-openedx-extensions/issues/168
=> fix: enrollment api to remove exam scores for multiple courses

futurex_openedx_extensions/dashboard/details/learners.py, futurex_openedx_extensions/helpers/querysets.py, tests/test_dashboard/test_details/test_details_learners.py, tests/test_helpers/test_querysets.py
Clean up code for enrolment API
=> fix: refactor code for enrollment api to make code cleaner

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/docs_src.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/helpers/extractors.py, tests/test_helpers/test_extractors.py
feat: better docs for `optional_field_tags`. 
Easy to show a table of tags with all related field names
=> feat: better docs for optional_field_tags

futurex_openedx_extensions/helpers/apps.py, test_utils/edx_platform_mocks_shared/bridgekeeper.py, test_utils/edx_platform_mocks_shared/lms/djangoapps/course_home_api/permissions.py, test_utils/edx_platform_mocks_shared/lms/djangoapps/courseware/rules.py
**Related issue:**: https://github.com/nelc/futurex-openedx-extensions/issues/151
**Dependent edx-platform PR:** https://github.com/nelc/edx-platform/pull/51
=> feat: give data researcher view  access to other learners progress page

tests/test_helpers/test_export_csv.py, tests/test_helpers/test_export_mixins.py, tests/test_helpers/test_tasks.py
refactor: enhance a few tests to use `base_data` fixture
we already have `base_data` ready to be used when sample data for tests is needed. This PR removes extra fixtures and replaces them with the sample data. It also removes the dependency of `tests/test_helpers/test_tasks.py` file on fixtures created in other files (every single test file should be able to run independently)
=> refactor: enhance a few tests to use base_data fixture

futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/helpers/converters.py, tests/test_dashboard/test_serializers.py, tests/test_helpers/test_converters.py
fix: unify datetime serialization
This will make all datetime fields rendered similar to `2024-12-31T03:03:00Z` by all serializers. So, we always have UTC representation, with no micro-seconds
=> fix: unify datetime serialization

futurex_openedx_extensions/dashboard/views.py
fix: allow dots in usernames in Roles APIs
* https://github.com/nelc/futurex-openedx-extensions/issues/207
=> fix: allow dots in usernames in Roles APIs

futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/roles.py, tests/test_dashboard/test_serializers.py, tests/test_helpers/test_roles.py
Roles listing API returns annoying records of roles that should be hidden by default. Now the API hides these roles, and shows them if-and-only-if the query parameter `include_hidden_roles=1` is passed
Hidden roles:
* `fx_api_access`
* `fx_api_access_global`
=> feat: filter for hidden roles

futurex_openedx_extensions/dashboard/docs_src.py, futurex_openedx_extensions/dashboard/urls.py, futurex_openedx_extensions/dashboard/views.py, tests/test_dashboard/test_views.py
Mocked Designer API for front-end.
- feat: Implement mock API to return the list of current draft configurations #217
- feat: Implement mock API to publish draft configurations #221
- feat: Implement mock API to return the current published configuration values #222
- feat: Implement mock API to update a configuration value #223
- feat: Implement mock API to delete the draft config #224
- feat: Implement mock API to create a new tenant #225
=> feat: mocked draft config api for theme designer

futurex_openedx_extensions/helpers/converters.py, tests/test_dashboard/test_serializers.py, tests/test_helpers/test_certificates.py, tests/test_helpers/test_converters.py
`relative_url_to_absolute_url` is not working properly. The related unit tests were mocking the `request.site.domain` in a wrong way. The domain does not contain the schema `http` or `https`, but the tests were assuming the schema already in the domain (my bad 🙄)
=> fix: relative_url_to_absolute_url not working properly

futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/helpers/settings/common_production.py, futurex_openedx_extensions/helpers/tenants.py, requirements/test-constraints-redwood.txt, requirements/test-constraints-sumac.txt, requirements/test.in, test_utils/edx_platform_mocks_shared/fake_models/models.py, test_utils/test_settings_common.py, tests/conftest.py, tests/test_dashboard/test_serializers.py, tests/test_helpers/test_apps.py, tests/test_helpers/test_tenants.py
Use SSO term instead of Nafath, and allow fetching user data when multiple SSO configs are available for the same site. The problem we have now is having multiple SSO entity IDs to be reported. Therefore, instead of `FX_NAFATH_ENTRY_ID` we'll use `FX_SSO_INFO` as a general term that contains a needed entity IDs along their basic information. The order of items in the `FX_SSO_INFO` settings will be respected when reporting the user's external ID. Only the first found ID will be reported
=> feat: use SSO term instead of Nafath

futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/helpers/exceptions.py, futurex_openedx_extensions/helpers/extractors.py, futurex_openedx_extensions/helpers/settings/common_production.py, test_utils/test_settings_common.py, tests/test_dashboard/test_serializers.py, tests/test_helpers/test_apps.py, tests/test_helpers/test_extractors.py
Refactor the way `external_id_extractor` is processed. We need to keep the settings serializable to be easily configured in the `yml` files
=> refactor: external_id_extractor

futurex_openedx_extensions/helpers/tenants.py, tests/test_helpers/test_tenants.py
Patch PR #268
this change has no effect on staging and production. It is only related to dev-stack. `route__domain` will always contains the site without the port number. This is why we need to have `LMS_BASE` in the information dictionary instead
=> fix: patch PR #268

futurex_openedx_extensions/helpers/converters.py, futurex_openedx_extensions/helpers/tenants.py, tests/test_helpers/test_converters.py
Draf config PUT is updating dictionary items instead of replacing them.
=> fix: draf config PUT missing up dictionaries

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/dashboard/views.py, tests/test_dashboard/test_views.py
feat: owner_user_id optional in create-tenant API
=> feat: owner_user_id optional in create-tenant API

tox.ini
Fix failing Github tests.
I found 2 options to fix it.
**Option1:**
- update pythonpath in setenv of tox
```
redwood: PYTHONPATH = {toxinidir}/test_utils/edx_platform_mocks_shared:{toxinidir}/test_utils/edx_platform_mocks_redwood:{env:PYTHONPATH:}
sumac: PYTHONPATH = {toxinidir}/test_utils/edx_platform_mocks_shared:{toxinidir}/test_utils/edx_platform_mocks_sumac:{env:PYTHONPATH:}
PYTHONPATH = {toxinidir}/test_utils/edx_platform_mocks_shared:{env:PYTHONPATH:}
```
**Option 2:**
- Packages are not recognised due to missing init files in folders. To fix this, we need to add __init__.py and update setup.py with following.
```
setup(
name='edx_platform_mocks_shared',
version='0.1.0',
py_modules=["boto3", "celery", "bridgekeeper"], //individual python files not packages
packages=find_packages() …
```
=> chore: update tox.ini for failing tests

futurex_openedx_extensions/dashboard/middlewares.py, test_utils/edx_platform_mocks_shared/eox_theming/edxapp_wrapper/models.py, test_utils/edx_platform_mocks_shared/fake_models/functions.py, tests/test_dashboard/test_middlewares.py
feat: enable theme-preview for other themes. if the theme of the tenant is not set to `indigo` yet, then preview will still work!
- #313
=> feat: enable theme-preview for other themes

futurex_openedx_extensions/dashboard/docs_src.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/urls.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/admin.py, futurex_openedx_extensions/helpers/settings/common_production.py, futurex_openedx_extensions/helpers/tenants.py, test_utils/test_settings_common.py, tests/conftest.py, tests/test_dashboard/test_serializers.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_tenants.py
Special access is two things:
1. Only system-staff users will be able to see/edit assets with slugs that start with an underscore `_`. This will make it easy to manage special assets for tenants without the probability of accidental update/deletion of those assets
2. Only system-staff users will be able to edit assets for the template tenant even though it's not listed in the accessible tenants. This will allow adding special assets that are not tenant dependent for any reason
**Note:** we're talking about the asset record in the database, not the asset file itself. The asset file will have it's own permissions according to the host that serves it
=> feat: system-staff users special access to tenant assets

futurex_openedx_extensions/__init__.py, futurex_openedx_extensions/helpers/signals.py, tests/test_helpers/test_signals.py
fix: tenant info invalidate cache
Only invalidate the cache if the template tenant assets are changed, not any tenant
=> fix: tenant info invalidate cache

futurex_openedx_extensions/dashboard/details/courses.py, futurex_openedx_extensions/dashboard/docs_src.py, futurex_openedx_extensions/dashboard/serializers.py, futurex_openedx_extensions/dashboard/urls.py, futurex_openedx_extensions/dashboard/views.py, futurex_openedx_extensions/helpers/extractors.py, tests/test_dashboard/test_views.py, tests/test_helpers/test_extractors.py
Added new API
`GET api/fx/courses/v1/feedback/`
Sample Repsonse 200:
```
{
"id": 2,
"course_id": "course-v1:nelp+111+11",
"course_name": "course 1 nelp",
"author_username": "user1",
"author_full_name": "user1",
"author_altternative_full_name": "عالي",
"author_email": "user1@exmaple.com",
"rating_content": 2,
"feedback": "another comment",
"public": true,
"rating_instructors": 4,
"recommended": true
}
```
=> feat: add api to list courses feedbacks
